# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZM36u3Q2zgti7oSwmJqVU_ro61xekATH

### 1.House Rental Prediction

---
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

df=pd.read_csv('https://raw.githubusercontent.com/edyoda/data-science-complete-tutorial/master/Data/house_rental_data.csv.txt')
df.head()

len(df)

df.drop('Unnamed: 0',1,inplace=True)

df.drop_duplicates(inplace=True)
len(df)

df.corr()

df.isna().sum()

sns.pointplot(df['Living.Room'],df.Price)

sns.pointplot(df['Floor'],df.Price)

sns.pointplot(df['TotalFloor'],df.Price)

sns.pointplot(df['Bathroom'],df.Price)

sns.pointplot(df['Bedroom'],df.Price)

sns.scatterplot(df.Sqft,df.Price)

# From plots, we can see the price is not dependent on floor and total floor

x=df.drop(['Floor',	'TotalFloor','Price'],1)
y=df.Price

xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=0)

price_lr=LinearRegression()
price_lr.fit(xtrain,ytrain)
price_lr.score(xtest,ytest)