# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZM36u3Q2zgti7oSwmJqVU_ro61xekATH

### 2.Employee Exit Prediction.

---
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

df.dtypes

df=pd.read_csv('https://raw.githubusercontent.com/edyoda/data-science-complete-tutorial/master/Data/HR_comma_sep.csv.txt')
df.head()

group=df.groupby('left').mean().reset_index()
group

sns.pointplot(group.left,group.satisfaction_level)

df.columns

sns.pointplot(group.left,group.promotion_last_5years)

sns.pointplot(df.salary, df.left)

sns.pointplot(df.left, df.sales)

salary={'low': 1, 'medium': 2, 'high': 3}

df.salary=df.salary.map(salary)
df.salary.unique()

# sales, last evaluation and work accident doesnt correlate with the rate of leaving the office

x=df[['satisfaction_level', 'number_project',
       'average_montly_hours', 'time_spend_company', 'left',
       'promotion_last_5years']]
y=df.left

xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=0)

logreg=LogisticRegression()
logreg.fit(xtrain,ytrain)

logreg.score(xtest,ytest)